// Embeds src/admin.html into a TS module so the Worker can serve it without
// filesystem access, and so tsx can import it in Node too.
import { readFile, writeFile } from "node:fs/promises";

const html = await readFile(new URL("../src/admin.html", import.meta.url), "utf8");
const escaped = html.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");

await writeFile(
  new URL("../src/ui.generated.ts", import.meta.url),
  `// GENERATED by scripts/build-ui.mjs from admin.html — do not edit.\nexport const ADMIN_HTML = \`${escaped}\`;\n`,
  "utf8",
);
console.log(`ui.generated.ts ← admin.html (${(html.length / 1024).toFixed(1)} KiB)`);
